### ISSUE TITLE
First release (footer)

### ISSUE THREAD

**Issue by riccardoSocialcities** [edgecowork/website-onepager#15]
- [x] Membresias
- [x] Locations
- [x] Eventos
- [x] Perks
- [x] Blog
- [x]  Prensa
- [x] FAQ
- [x] TOS & PP

**Comment by diegomorales85** [comment]
Eventos: 
https://docs.google.com/document/d/1ii3ToHaB0frJcaH_sD04TPIvXT1-kdrGbcMGniZhetg/edit

Added subscribe to future events on page..

**Comment by diegomorales85** [comment]
Prensa: 
https://docs.google.com/document/d/1bQPJM2bkRNlMqi5BxbtId6Uxj_H75DvnLR4NlNbtwWY/edit

**Comment by diegomorales85** [comment]
Change the CTA button on the footer from “Sign in” to “Subscribe me" . And Fix the the coloring of the text in the footer.

**Comment by diegomorales85** [comment]
Perks: 
https://docs.google.com/document/d/1JqGXWYM6JPs50cCiJxLDAi8J4q4D2puRbC4GJG1heCQ/edit

**Comment by diegomorales85** [comment]
TOS: 
https://docs.google.com/document/d/1uWR5cZJgdlV8No5JyzkrJo8SBxK_75PDq1DiPir2TO8/edit#

**Comment by diegomorales85** [comment]
FAQ: 
https://docs.google.com/document/d/1TYABRd4sycyA7Ux0xIO_YDMLYVJzxup40Ikk-npIQ6c/edit

**Comment by diegomorales85** [comment]
Footer categories:
Categorias del Footer v2

**Membresías**
Day Pass
Hot Desk part-time
Hot Desk
Dedicated Desk
Meeting Room 
Oficina Virtual
Oficina Privada
Corporativo

**Epic sh*t**
Eventos
Blog
Alianzas

**Empresa**
Contacto
Prensa
Preguntas frecuentes
Términos y Condiciones

**Social Media icons**
Facebook
LinkedIn
Twitter
Google+
Instagram

**Comment by diegomorales85** [comment]
Add App store buttons in footer, below social icons: 
https://drive.google.com/open?id=0B879Nw5i5bMDYUlESUlPUi1BZ3c
